
#@package _group_
prevention:
  _target_: ".data.prevention_data_iter.read_frame_from_iter"
  path_to_video: "/home/iccs/Desktop/isense/events/intention_prediction/video.avi"

  _path_to_video_train: "/home/iccs/Desktop/isense/events/intention_prediction/video_train.avi"
  _path_to_video_val: "/home/iccs/Desktop/isense/events/intention_prediction/video_val.avi"
  _path_to_video_test: "/home/iccs/Desktop/isense/events/intention_prediction/video_test.avi"

  path_to_label: "/home/iccs/Desktop/isense/events/intention_prediction/detection_camera1/lane_changes_preprocessed.txt"
  dataset_root: "/home/iccs/Desktop/isense/events/intention_prediction/"
  dataset_name: "prevention"
  dataset_size: 

  splits:
  - train: 0.8
  - val: 0.1
  - test: 0.1
