
#@package _group_
_target_: intention_prediction.data.prevention_data_iter
_args_:  
  path_to_video: "/home/iccs/Desktop/isense/events/intention_prediction/video.avi"
  path_to_label: "/home/iccs/Desktop/isense/events/intention_prediction/detection_camera1/lane_changes.txt"
  dataset_root: "/home/iccs/Desktop/isense/events/intention_prediction/"
  dataset_name: "prevention"
  dataset_size: 
  splits:
  - train: 0.8
  - val: 0.1
  - test: 0.1

batch_size: 50
